const sharp = require('sharp');
const path = require('path');
const fs = require('fs');

/**
 * Image output sizes:
 *   - carousel:  800w  WebP + JPG fallback  (what most users see)
 *   - lightbox:  1600w WebP                 (click-to-expand full res)
 *
 * All outputs maintain 4:5 aspect ratio via cover-crop.
 * Quality is tuned for poster artwork — slightly higher than photo defaults.
 */
const OUTPUTS = [
  { suffix: '',          width: 800,  height: 1000, format: 'webp', quality: 82 },
  { suffix: '',          width: 800,  height: 1000, format: 'jpg',  quality: 80 },
  { suffix: '-full',     width: 1600, height: 2000, format: 'webp', quality: 80 },
];

async function processPosters({ posters, originalsDir, outputDir, configPath }) {
  fs.mkdirSync(outputDir, { recursive: true });

  const results = [];
  const configEntries = [];

  for (let i = 0; i < posters.length; i++) {
    const poster = posters[i];
    const srcPath = path.join(originalsDir, poster.file);

    if (!fs.existsSync(srcPath)) {
      console.warn(`Skipping missing file: ${poster.file}`);
      continue;
    }

    const slug = poster.slug || path.basename(poster.file, path.extname(poster.file))
      .toLowerCase().replace(/[^a-z0-9]+/g, '-');

    const generated = [];

    for (const output of OUTPUTS) {
      const ext = output.format === 'jpg' ? 'jpg' : 'webp';
      const filename = `${slug}${output.suffix}.${ext}`;
      const destPath = path.join(outputDir, filename);

      let pipeline = sharp(srcPath)
        .resize(output.width, output.height, {
          fit: 'cover',
          position: 'centre'
        });

      if (output.format === 'webp') {
        pipeline = pipeline.webp({ quality: output.quality, effort: 4 });
      } else {
        pipeline = pipeline.jpeg({ quality: output.quality, mozjpeg: true });
      }

      await pipeline.toFile(destPath);

      const stats = fs.statSync(destPath);
      generated.push({ filename, size: stats.size });
    }

    results.push({ slug, generated });

    // Build config entry
    const entry = {
      slug,
      webp: `${slug}.webp`,
      jpg: `${slug}.jpg`,
      full: `${slug}-full.webp`,
    };
    if (poster.alt) entry.alt = poster.alt;
    if (poster.title) entry.title = poster.title;
    configEntries.push(entry);
  }

  // Write events-config.json
  const config = {
    comment: "Generated by poster-manager. Order matches carousel display order.",
    events: configEntries
  };
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');

  // Summary
  const totalSize = results.reduce((sum, r) =>
    sum + r.generated.reduce((s, g) => s + g.size, 0), 0);

  return {
    processed: results.length,
    totalFiles: results.reduce((sum, r) => sum + r.generated.length, 0),
    totalSize,
    totalSizeMB: (totalSize / 1024 / 1024).toFixed(1)
  };
}

module.exports = { processPosters };
