# Generates the official REALITY QR codes for https://realitydn.com
# (canonical apex — www.realitydn.com 301s here, so encoding the apex
# saves every scan a redirect hop; the *printed* URL stays www.realitydn.com).
#
# Outputs to brand-assets/qr/:
#   reality-qr-ink-on-white.png   2160px, for print on white
#   reality-qr-ink-on-cream.png   2160px, for digital/cream surfaces
#   reality-qr-ink-transparent.png 2160px, transparent background
#   reality-qr-ink.svg            vector, transparent background
#   reality-qr-matrix.js          module matrix for the Poster Studio embed
#
# Run:  python tools/generate-qr.py

import json
import os

import qrcode
from PIL import Image

URL = "https://realitydn.com"
INK = (13, 9, 5)        # #0d0905
CREAM = (255, 251, 241)  # #fffbf1
WHITE = (255, 255, 255)
QUIET = 4               # quiet-zone modules per side (QR spec)
PX = 2160               # PNG output size

OUT = os.path.join(os.path.dirname(__file__), "..", "brand-assets", "qr")
os.makedirs(OUT, exist_ok=True)

qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=QUIET)
qr.add_data(URL)
qr.make(fit=True)
matrix = qr.get_matrix()  # includes border rows/cols
n_total = len(matrix)
n_data = n_total - 2 * QUIET
print(f"URL: {URL}")
print(f"QR version {qr.version} -> {n_data}x{n_data} modules (+{QUIET} quiet zone)")


def render_png(path, fg, bg):
    """Render at integer module scale, then upscale with NEAREST to PX."""
    scale = max(1, PX // n_total)
    size = n_total * scale
    mode = "RGBA" if bg is None else "RGB"
    blank = (0, 0, 0, 0) if bg is None else bg
    img = Image.new(mode, (size, size), blank)
    px = img.load()
    fgpx = fg + (255,) if bg is None else fg
    for y, row in enumerate(matrix):
        for x, cell in enumerate(row):
            if cell:
                for dy in range(scale):
                    for dx in range(scale):
                        px[x * scale + dx, y * scale + dy] = fgpx
    img = img.resize((PX, PX), Image.NEAREST)
    img.save(path)
    print("wrote", os.path.relpath(path))


def render_svg(path, fg_hex):
    cells = []
    for y, row in enumerate(matrix):
        for x, cell in enumerate(row):
            if cell:
                cells.append(f'<rect x="{x}" y="{y}" width="1" height="1"/>')
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {n_total} {n_total}" '
        f'shape-rendering="crispEdges"><g fill="{fg_hex}">{"".join(cells)}</g></svg>'
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg)
    print("wrote", os.path.relpath(path))


render_png(os.path.join(OUT, "reality-qr-ink-on-white.png"), INK, WHITE)
render_png(os.path.join(OUT, "reality-qr-ink-on-cream.png"), INK, CREAM)
render_png(os.path.join(OUT, "reality-qr-ink-transparent.png"), INK, None)
render_svg(os.path.join(OUT, "reality-qr-ink.svg"), "#0d0905")

# Matrix for the Poster Studio (data modules only — the studio adds its own
# quiet zone as padding). Rows are '0'/'1' strings to keep the file small.
data_rows = [
    "".join("1" if cell else "0" for cell in row[QUIET:-QUIET])
    for row in matrix[QUIET:-QUIET]
]
with open(os.path.join(OUT, "reality-qr-matrix.js"), "w", encoding="utf-8") as f:
    f.write("/* QR module matrix for https://realitydn.com — generated by tools/generate-qr.py */\n")
    f.write("const REALITY_QR_ROWS = " + json.dumps(data_rows, indent=0) + ";\n")
print("wrote", os.path.relpath(os.path.join(OUT, "reality-qr-matrix.js")))

# ---- decode verification (OpenCV) ----
import cv2  # noqa: E402

for name in ["reality-qr-ink-on-white.png", "reality-qr-ink-on-cream.png"]:
    img = cv2.imread(os.path.join(OUT, name))
    decoded, _, _ = cv2.QRCodeDetector().detectAndDecode(img)
    status = "OK" if decoded == URL else f"MISMATCH ({decoded!r})"
    print(f"decode {name}: {status}")

# Small-size sanity: does it still decode at WhatsApp-thumbnail-ish scale?
img = cv2.imread(os.path.join(OUT, "reality-qr-ink-on-white.png"))
small = cv2.resize(img, (120, 120), interpolation=cv2.INTER_AREA)
decoded, _, _ = cv2.QRCodeDetector().detectAndDecode(small)
print("decode at 120px:", "OK" if decoded == URL else f"failed ({decoded!r})")
